openapi: 3.0.3
info:
  version: "4.0"
  title: RealEstateCore
  license:
    name: BSD
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: RealEstateCore Consortium
    url: https://realestatecore.io/
    email: hello@realestatecore.io
  description: 
components:
  parameters:
    pageParam:
      name: page
      description: If the result set is large, pagination across the results can be employed; in that case, this parameter defines the page number (zero-indexed) that is requested by the client. The number of items included in each page is defined by the 'size' parameter. Default is 0, i.e., the first results page is returned.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 0
        default: 0
        enum: 
      style: 
      $ref: 
      in: query
    sizeParam:
      name: size
      description: The number of items to display on a returned results page (see the page parameter).
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 100
        default: 20
        enum: 
      style: 
      $ref: 
      in: query
    sortParam:
      name: sort
      description: The field and direction to sort results on.
      required: false
      schema:
        $ref: '#/components/schemas/SortingSchema'
      style: deepObject
      $ref: 
      in: query
  schemas:
    HydraCollectionWrapper:
      type: object
      required:
      - '@context'
      - '@type'
      - hydra:member
      properties:
        '@context':
          $ref: '#/components/schemas/Context'
        '@type':
          type: string
          format: 
          minimum: 
          maximum: 0
          default: hydra:Collection
          enum: 
        hydra:totalItems:
          type: integer
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        hydra:view:
          type: object
          required: 
          properties:
            '@id':
              type: string
              format: uri
              minimum: 
              maximum: 0
              default: 
              enum: 
            '@type':
              type: string
              format: 
              minimum: 
              maximum: 0
              default: hydra:PartialCollectionView
              enum: 
            hydra:first:
              type: string
              format: 
              minimum: 
              maximum: 0
              default: 
              enum: 
            hydra:previous:
              type: string
              format: 
              minimum: 
              maximum: 0
              default: 
              enum: 
            hydra:next:
              type: string
              format: 
              minimum: 
              maximum: 0
              default: 
              enum: 
            hydra:last:
              type: string
              format: 
              minimum: 
              maximum: 0
              default: 
              enum: 
          maxproperties: 0
          minproperties: 0
      maxproperties: 0
      minproperties: 0
    IntegerFilter:
      type: object
      required: 
      properties:
        eq:
          type: integer
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        lt:
          type: integer
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        lte:
          type: integer
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        gt:
          type: integer
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        gte:
          type: integer
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
      maxproperties: 0
      minproperties: 0
    NumberFilter:
      type: object
      required: 
      properties:
        eq:
          type: number
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        lt:
          type: number
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        lte:
          type: number
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        gt:
          type: number
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        gte:
          type: number
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
      maxproperties: 0
      minproperties: 0
    StringFilter:
      type: object
      required: 
      properties:
        eq:
          type: string
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        contains:
          type: string
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        regex:
          type: string
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
      maxproperties: 0
      minproperties: 0
    DateTimeFilter:
      type: object
      required: 
      properties:
        eq:
          type: string
          format: date-time
          minimum: 
          maximum: 0
          default: 
          enum: 
        starting:
          type: string
          format: date-time
          minimum: 
          maximum: 0
          default: 
          enum: 
        ending:
          type: string
          format: date-time
          minimum: 
          maximum: 0
          default: 
          enum: 
        before:
          type: string
          format: date-time
          minimum: 
          maximum: 0
          default: 
          enum: 
        after:
          type: string
          format: date-time
          minimum: 
          maximum: 0
          default: 
          enum: 
        latest:
          type: boolean
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
      maxproperties: 0
      minproperties: 0
    SortingSchema:
      type: object
      required: 
      properties:
        asc:
          type: string
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
        desc:
          type: string
          format: 
          minimum: 
          maximum: 0
          default: 
          enum: 
      maxproperties: 0
      minproperties: 0
paths: {}
servers:
- url: http://localhost:8080/
